name: tk_suixi_news
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^2.1.7
  flutter_swiper : ^1.1.6
  flutter_screenutil: ^0.5.2
  url_launcher: ^5.0.3
  flutter_easyrefresh: ^1.2.7
  provider: 3.0.0+1
  fluttertoast: ^3.1.0
  fluro: ^1.5.0
  flutter_html: ^0.10.4
  shared_preferences: ^0.5.3+2
  chewie: ^0.9.7
  video_player: ^0.10.1+3
  badges: ^1.0.3 #角标

  image_picker: ^0.6.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/place_holder_image.png
    - lib/assets/mine_page_header.png
    - lib/assets/mine_favo_icon.png  #我的收藏
    - lib/assets/mine_recen_icon.png  #最近浏览
    - lib/assets/mine_list_icon.png  #我的帖子
    - lib/assets/mine_ask_icon.png #问政记录
    - lib/assets/mine_message_icon.png  #我的消息
    - lib/assets/mine_gift_icon.png  #兑换记录
    - lib/assets/mine_love_icon.png  #关注板块
    - lib/assets/mine_building_icon.png  #关于我们
    - lib/assets/circle.png  #朋友圈
    - lib/assets/weibo.png  #微博
    - lib/assets/wechat.png  #微信
    - lib/assets/qq.png  #qq
    - lib/assets/score_shop.png  #qq
    - lib/assets/title_server_sec.png  #标题的标签
    - lib/assets/login_assets/1.png  #QQ登录
    - lib/assets/login_assets/2.png  #微信登录
    - lib/assets/login_assets/3.png  #微博登录
    - lib/assets/login_assets/logo.png  #微博登录
    - lib/assets/login_assets/choose.png  #选中
    - lib/assets/login_assets/unchoose.png  #未选中
    - lib/assets/delete.png  #未选中
    - lib/assets/add_photo.png
    - lib/assets/dislike.png #不喜欢
    - lib/assets/like.png #喜欢
    - lib/assets/navigationBarTitle.png #导航栏上的标题
    - lib/assets/home_tab.png #未选中
    - lib/assets/home_selected_tab.png #选中
    - lib/assets/camera_tab.png
    - lib/assets/camera_selected_tab.png
    - lib/assets/server_tab.png
    - lib/assets/server_tab_selected.png
    - lib/assets/mine_tab.png
    - lib/assets/mine_selected_tab.png
    - lib/assets/avatar_default.png
    - lib/assets/gold_coins.png #个人页面的金币
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
